import os

GITHUB_TOKEN = os.environ['SELFBOARD_GITHUB_TOKEN']
GITLAB_TOKEN = os.environ['SELFBOARD_GITLAB_TOKEN']
SLACK_TOKEN = os.environ['SELFBOARD_SLACK_TOKEN']

GITLAB_URL = os.getenv('SELFBOARD_GITLAB_URL', 'https://gitlab.com')
GITLAB_GROUP_ID = os.getenv('SELFBOARD_GITLAB_GROUP_ID', '7348696')
GITLAB_DEFAULT_LEVEL = os.getenv('SELFBOARD_GITLAB_DEFAULT_LEVEL', '40')
